'''
Like [1], we use a cross-validation grid search method to select k (target_dim, number of shapelets) and
η (len_shapelet_ratio, the ratio of the time series length).

[1] Grabocka, Josif, et al. "Learning time-series shapelets." Proceedings of the 20th ACM SIGKDD international conference
on Knowledge discovery and data mining. 2014.
'''


ucr_hyp_dict_10 = {'AllGestureWiimoteX': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteY': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteZ': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'ArrowHead': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'BME': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Car': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'CBF': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'Chinatown': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'CinCECGTorso': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'ChlorineConcentration': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'Computers': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'CricketX': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'CricketY': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'CricketZ': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Crop': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'DiatomSizeReduction': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'DistalPhalanxOutlineAgeGroup': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'DistalPhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'DistalPhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'DodgerLoopGame': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'DodgerLoopWeekend': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'Earthquakes': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'ECG200': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'ECG5000': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'ECGFiveDays': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'ElectricDevices': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'EOGHorizontalSignal': {'target_dim': 5, 'len_shapelet_ratio': 0.4},
                   'EOGVerticalSignal': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'EthanolLevel': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'FaceAll': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'FacesUCR': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'Fish': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FordA': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'FordB': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'FreezerRegularTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'FreezerSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'GesturePebbleZ1': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'GesturePebbleZ2': {'target_dim': 5, 'len_shapelet_ratio': 0.5},
                   'GunPoint': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'GunPointAgeSpan': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'GunPointMaleVersusFemale': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'GunPointOldVersusYoung': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Ham': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'HandOutlines': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'Haptics': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'Herring': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'HouseTwenty': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'InlineSkate': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'InsectEPGRegularTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'InsectEPGSmallTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.4},
                   'InsectWingbeatSound': {'target_dim': 5, 'len_shapelet_ratio': 0.4},
                   'ItalyPowerDemand': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'LargeKitchenAppliances': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Lightning2': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'Mallat': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Meat': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'MedicalImages': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'MelbournePedestrian': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'MiddlePhalanxOutlineAgeGroup': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'MiddlePhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'MiddlePhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'MixedShapesRegularTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'MixedShapesSmallTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'MoteStrain': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'NonInvasiveFetalECGThorax1': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'NonInvasiveFetalECGThorax2': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'OSULeaf': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'PhalangesOutlinesCorrect': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Phoneme': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'PLAID': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'Plane': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'PowerCons': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'ProximalPhalanxOutlineAgeGroup': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'ProximalPhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'ProximalPhalanxTW': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'RefrigerationDevices': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'ScreenType': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'SemgHandGenderCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'SemgHandMovementCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'SemgHandSubjectCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'ShapeletSim': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'SmallKitchenAppliances': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'SmoothSubspace': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'SonyAIBORobotSurface1': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'SonyAIBORobotSurface2': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'StarLightCurves': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'Strawberry': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'SwedishLeaf': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'Symbols': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'SyntheticControl': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'ToeSegmentation1': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'ToeSegmentation2': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'Trace': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'TwoLeadECG': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'TwoPatterns': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'UMD': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryAll': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'UWaveGestureLibraryX': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryY': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'UWaveGestureLibraryZ': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'Wafer': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Wine': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'WordSynonyms': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'Worms': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'WormsTwoClass': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Yoga': {'target_dim': 5, 'len_shapelet_ratio': 0.6}}

ucr_hyp_dict_20 = {'AllGestureWiimoteX': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteY': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteZ': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'ArrowHead': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'BME': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'Car': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'CBF': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'Chinatown': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'CinCECGTorso': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'ChlorineConcentration': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Computers': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'CricketX': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'CricketY': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'CricketZ': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Crop': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'DiatomSizeReduction': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'DistalPhalanxOutlineAgeGroup': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'DistalPhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'DistalPhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.4},
                   'DodgerLoopGame': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'DodgerLoopWeekend': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'Earthquakes': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'ECG200': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'ECG5000': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'ECGFiveDays': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'ElectricDevices': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'EOGHorizontalSignal': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'EOGVerticalSignal': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'EthanolLevel': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'FaceAll': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'FacesUCR': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Fish': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FordA': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FordB': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FreezerRegularTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'FreezerSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'GesturePebbleZ1': {'target_dim': 10, 'len_shapelet_ratio': 0.5},
                   'GesturePebbleZ2': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'GunPoint': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'GunPointAgeSpan': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'GunPointMaleVersusFemale': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'GunPointOldVersusYoung': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'Ham': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'HandOutlines': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'Haptics': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Herring': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'HouseTwenty': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'InlineSkate': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'InsectEPGRegularTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'InsectEPGSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'InsectWingbeatSound': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'ItalyPowerDemand': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'LargeKitchenAppliances': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Lightning2': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'Mallat': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Meat': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'MedicalImages': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'MelbournePedestrian': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'MiddlePhalanxOutlineAgeGroup': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'MiddlePhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'MiddlePhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'MixedShapesRegularTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'MixedShapesSmallTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'MoteStrain': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'NonInvasiveFetalECGThorax1': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'NonInvasiveFetalECGThorax2': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'OSULeaf': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'PhalangesOutlinesCorrect': {'target_dim': 5, 'len_shapelet_ratio': 0.5},
                   'Phoneme': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'PLAID': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'Plane': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'PowerCons': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'ProximalPhalanxOutlineAgeGroup': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'ProximalPhalanxOutlineCorrect': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'ProximalPhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'RefrigerationDevices': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'ScreenType': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'SemgHandGenderCh2': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'SemgHandMovementCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'SemgHandSubjectCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.2},
                   'ShapeletSim': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'SmallKitchenAppliances': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'SmoothSubspace': {'target_dim': 10, 'len_shapelet_ratio': 0.5},
                   'SonyAIBORobotSurface1': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'SonyAIBORobotSurface2': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'StarLightCurves': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'Strawberry': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'SwedishLeaf': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Symbols': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'SyntheticControl': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'ToeSegmentation1': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'ToeSegmentation2': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'Trace': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'TwoLeadECG': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'TwoPatterns': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'UMD': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryAll': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'UWaveGestureLibraryX': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'UWaveGestureLibraryY': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryZ': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'Wafer': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'Wine': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'WordSynonyms': {'target_dim': 10, 'len_shapelet_ratio': 0.5},
                   'Worms': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'WormsTwoClass': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Yoga': {'target_dim': 10, 'len_shapelet_ratio': 0.7}}

ucr_hyp_dict_40 = {'AllGestureWiimoteX': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteY': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'AllGestureWiimoteZ': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'ArrowHead': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'BME': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Car': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'CBF': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'Chinatown': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'CinCECGTorso': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'ChlorineConcentration': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'Computers': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'CricketX': {'target_dim': 2, 'len_shapelet_ratio': 0.6},
                   'CricketY': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'CricketZ': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'Crop': {'target_dim': 5, 'len_shapelet_ratio': 0.7},
                   'DiatomSizeReduction': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'DistalPhalanxOutlineAgeGroup': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'DistalPhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'DistalPhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'DodgerLoopGame': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'DodgerLoopWeekend': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'Earthquakes': {'target_dim': 10, 'len_shapelet_ratio': 0.4},
                   'ECG200': {'target_dim': 2, 'len_shapelet_ratio': 0.4},
                   'ECG5000': {'target_dim': 10, 'len_shapelet_ratio': 0.5},
                   'ECGFiveDays': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'ElectricDevices': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'EOGHorizontalSignal': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'EOGVerticalSignal': {'target_dim': 5, 'len_shapelet_ratio': 0.4},
                   'EthanolLevel': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'FaceAll': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'FacesUCR': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Fish': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'FordA': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FordB': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'FreezerRegularTrain': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'FreezerSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'GesturePebbleZ1': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'GesturePebbleZ2': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'GunPoint': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'GunPointAgeSpan': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'GunPointMaleVersusFemale': {'target_dim': 10, 'len_shapelet_ratio': 0.5},
                   'GunPointOldVersusYoung': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Ham': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'HandOutlines': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'Haptics': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'Herring': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'HouseTwenty': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'InlineSkate': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'InsectEPGRegularTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'InsectEPGSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'InsectWingbeatSound': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'ItalyPowerDemand': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'LargeKitchenAppliances': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'Lightning2': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'Mallat': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'Meat': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'MedicalImages': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'MelbournePedestrian': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'MiddlePhalanxOutlineAgeGroup': {'target_dim': 2, 'len_shapelet_ratio': 0.1},
                   'MiddlePhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'MiddlePhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'MixedShapesRegularTrain': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'MixedShapesSmallTrain': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'MoteStrain': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'NonInvasiveFetalECGThorax1': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'NonInvasiveFetalECGThorax2': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'OSULeaf': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'PhalangesOutlinesCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'Phoneme': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'PLAID': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'Plane': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'PowerCons': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'ProximalPhalanxOutlineAgeGroup': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'ProximalPhalanxOutlineCorrect': {'target_dim': 2, 'len_shapelet_ratio': 0.3},
                   'ProximalPhalanxTW': {'target_dim': 5, 'len_shapelet_ratio': 0.1},
                   'RefrigerationDevices': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'ScreenType': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'SemgHandGenderCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.1},
                   'SemgHandMovementCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.3},
                   'SemgHandSubjectCh2': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'ShapeletSim': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'SmallKitchenAppliances': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'SmoothSubspace': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'SonyAIBORobotSurface1': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'SonyAIBORobotSurface2': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'StarLightCurves': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'Strawberry': {'target_dim': 5, 'len_shapelet_ratio': 0.2},
                   'SwedishLeaf': {'target_dim': 2, 'len_shapelet_ratio': 0.5},
                   'Symbols': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'SyntheticControl': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'ToeSegmentation1': {'target_dim': 2, 'len_shapelet_ratio': 0.7},
                   'ToeSegmentation2': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Trace': {'target_dim': 2, 'len_shapelet_ratio': 0.8},
                   'TwoLeadECG': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'TwoPatterns': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'UMD': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryAll': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'UWaveGestureLibraryX': {'target_dim': 10, 'len_shapelet_ratio': 0.7},
                   'UWaveGestureLibraryY': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'UWaveGestureLibraryZ': {'target_dim': 10, 'len_shapelet_ratio': 0.8},
                   'Wafer': {'target_dim': 5, 'len_shapelet_ratio': 0.3},
                   'Wine': {'target_dim': 2, 'len_shapelet_ratio': 0.2},
                   'WordSynonyms': {'target_dim': 10, 'len_shapelet_ratio': 0.6},
                   'Worms': {'target_dim': 5, 'len_shapelet_ratio': 0.6},
                   'WormsTwoClass': {'target_dim': 5, 'len_shapelet_ratio': 0.8},
                   'Yoga': {'target_dim': 10, 'len_shapelet_ratio': 0.7}}

ucr_hyp_prompt_10 = {'AllGestureWiimoteX': {'prompt_toolkit_series_i': 8},
                     'AllGestureWiimoteY': {'prompt_toolkit_series_i': 6},
                     'AllGestureWiimoteZ': {'prompt_toolkit_series_i': 5}, 'ArrowHead': {'prompt_toolkit_series_i': 6},
                     'BME': {'prompt_toolkit_series_i': 4}, 'Car': {'prompt_toolkit_series_i': 2},
                     'CBF': {'prompt_toolkit_series_i': 1}, 'Chinatown': {'prompt_toolkit_series_i': 6},
                     'CinCECGTorso': {'prompt_toolkit_series_i': 2},
                     'ChlorineConcentration': {'prompt_toolkit_series_i': 2},
                     'Computers': {'prompt_toolkit_series_i': 8}, 'CricketX': {'prompt_toolkit_series_i': 7},
                     'CricketY': {'prompt_toolkit_series_i': 7}, 'CricketZ': {'prompt_toolkit_series_i': 4},
                     'Crop': {'prompt_toolkit_series_i': 2}, 'DiatomSizeReduction': {'prompt_toolkit_series_i': 6},
                     'DistalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 5},
                     'DistalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 2},
                     'DistalPhalanxTW': {'prompt_toolkit_series_i': 1},
                     'DodgerLoopGame': {'prompt_toolkit_series_i': 6},
                     'DodgerLoopWeekend': {'prompt_toolkit_series_i': 8}, 'Earthquakes': {'prompt_toolkit_series_i': 3},
                     'ECG200': {'prompt_toolkit_series_i': 1}, 'ECG5000': {'prompt_toolkit_series_i': 5},
                     'ECGFiveDays': {'prompt_toolkit_series_i': 3}, 'ElectricDevices': {'prompt_toolkit_series_i': 4},
                     'EOGHorizontalSignal': {'prompt_toolkit_series_i': 3},
                     'EOGVerticalSignal': {'prompt_toolkit_series_i': 7},
                     'EthanolLevel': {'prompt_toolkit_series_i': 6}, 'FaceAll': {'prompt_toolkit_series_i': 4},
                     'FacesUCR': {'prompt_toolkit_series_i': 4}, 'Fish': {'prompt_toolkit_series_i': 5},
                     'FordA': {'prompt_toolkit_series_i': 2}, 'FordB': {'prompt_toolkit_series_i': 5},
                     'FreezerRegularTrain': {'prompt_toolkit_series_i': 3},
                     'FreezerSmallTrain': {'prompt_toolkit_series_i': 5},
                     'GesturePebbleZ1': {'prompt_toolkit_series_i': 3},
                     'GesturePebbleZ2': {'prompt_toolkit_series_i': 4}, 'GunPoint': {'prompt_toolkit_series_i': 4},
                     'GunPointAgeSpan': {'prompt_toolkit_series_i': 3},
                     'GunPointMaleVersusFemale': {'prompt_toolkit_series_i': 1},
                     'GunPointOldVersusYoung': {'prompt_toolkit_series_i': 3}, 'Ham': {'prompt_toolkit_series_i': 6},
                     'HandOutlines': {'prompt_toolkit_series_i': 3}, 'Haptics': {'prompt_toolkit_series_i': 4},
                     'Herring': {'prompt_toolkit_series_i': 7}, 'HouseTwenty': {'prompt_toolkit_series_i': 8},
                     'InlineSkate': {'prompt_toolkit_series_i': 6},
                     'InsectEPGRegularTrain': {'prompt_toolkit_series_i': 1},
                     'InsectEPGSmallTrain': {'prompt_toolkit_series_i': 1},
                     'InsectWingbeatSound': {'prompt_toolkit_series_i': 1},
                     'ItalyPowerDemand': {'prompt_toolkit_series_i': 2},
                     'LargeKitchenAppliances': {'prompt_toolkit_series_i': 8},
                     'Lightning2': {'prompt_toolkit_series_i': 5}, 'Mallat': {'prompt_toolkit_series_i': 7},
                     'Meat': {'prompt_toolkit_series_i': 7}, 'MedicalImages': {'prompt_toolkit_series_i': 4},
                     'MelbournePedestrian': {'prompt_toolkit_series_i': 6},
                     'MiddlePhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 7},
                     'MiddlePhalanxOutlineCorrect': {'prompt_toolkit_series_i': 5},
                     'MiddlePhalanxTW': {'prompt_toolkit_series_i': 6},
                     'MixedShapesRegularTrain': {'prompt_toolkit_series_i': 1},
                     'MixedShapesSmallTrain': {'prompt_toolkit_series_i': 8},
                     'MoteStrain': {'prompt_toolkit_series_i': 1},
                     'NonInvasiveFetalECGThorax1': {'prompt_toolkit_series_i': 1},
                     'NonInvasiveFetalECGThorax2': {'prompt_toolkit_series_i': 3},
                     'OSULeaf': {'prompt_toolkit_series_i': 2},
                     'PhalangesOutlinesCorrect': {'prompt_toolkit_series_i': 5},
                     'Phoneme': {'prompt_toolkit_series_i': 8}, 'PLAID': {'prompt_toolkit_series_i': 3},
                     'Plane': {'prompt_toolkit_series_i': 3}, 'PowerCons': {'prompt_toolkit_series_i': 3},
                     'ProximalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 7},
                     'ProximalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 6},
                     'ProximalPhalanxTW': {'prompt_toolkit_series_i': 2},
                     'RefrigerationDevices': {'prompt_toolkit_series_i': 5},
                     'ScreenType': {'prompt_toolkit_series_i': 4}, 'SemgHandGenderCh2': {'prompt_toolkit_series_i': 3},
                     'SemgHandMovementCh2': {'prompt_toolkit_series_i': 6},
                     'SemgHandSubjectCh2': {'prompt_toolkit_series_i': 2},
                     'ShapeletSim': {'prompt_toolkit_series_i': 6},
                     'SmallKitchenAppliances': {'prompt_toolkit_series_i': 2},
                     'SmoothSubspace': {'prompt_toolkit_series_i': 1},
                     'SonyAIBORobotSurface1': {'prompt_toolkit_series_i': 1},
                     'SonyAIBORobotSurface2': {'prompt_toolkit_series_i': 1},
                     'StarLightCurves': {'prompt_toolkit_series_i': 8}, 'Strawberry': {'prompt_toolkit_series_i': 1},
                     'SwedishLeaf': {'prompt_toolkit_series_i': 5}, 'Symbols': {'prompt_toolkit_series_i': 4},
                     'SyntheticControl': {'prompt_toolkit_series_i': 3},
                     'ToeSegmentation1': {'prompt_toolkit_series_i': 5},
                     'ToeSegmentation2': {'prompt_toolkit_series_i': 3}, 'Trace': {'prompt_toolkit_series_i': 6},
                     'TwoLeadECG': {'prompt_toolkit_series_i': 8}, 'TwoPatterns': {'prompt_toolkit_series_i': 2},
                     'UMD': {'prompt_toolkit_series_i': 1}, 'UWaveGestureLibraryAll': {'prompt_toolkit_series_i': 7},
                     'UWaveGestureLibraryX': {'prompt_toolkit_series_i': 3},
                     'UWaveGestureLibraryY': {'prompt_toolkit_series_i': 1},
                     'UWaveGestureLibraryZ': {'prompt_toolkit_series_i': 6}, 'Wafer': {'prompt_toolkit_series_i': 4},
                     'Wine': {'prompt_toolkit_series_i': 3}, 'WordSynonyms': {'prompt_toolkit_series_i': 5},
                     'Worms': {'prompt_toolkit_series_i': 7}, 'WormsTwoClass': {'prompt_toolkit_series_i': 5},
                     'Yoga': {'prompt_toolkit_series_i': 6}}

ucr_hyp_prompt_20 = {'AllGestureWiimoteX': {'prompt_toolkit_series_i': 4},
                     'AllGestureWiimoteY': {'prompt_toolkit_series_i': 6},
                     'AllGestureWiimoteZ': {'prompt_toolkit_series_i': 7}, 'ArrowHead': {'prompt_toolkit_series_i': 8},
                     'BME': {'prompt_toolkit_series_i': 1}, 'Car': {'prompt_toolkit_series_i': 1},
                     'CBF': {'prompt_toolkit_series_i': 1}, 'Chinatown': {'prompt_toolkit_series_i': 5},
                     'CinCECGTorso': {'prompt_toolkit_series_i': 1},
                     'ChlorineConcentration': {'prompt_toolkit_series_i': 8},
                     'Computers': {'prompt_toolkit_series_i': 3}, 'CricketX': {'prompt_toolkit_series_i': 6},
                     'CricketY': {'prompt_toolkit_series_i': 3}, 'CricketZ': {'prompt_toolkit_series_i': 3},
                     'Crop': {'prompt_toolkit_series_i': 4}, 'DiatomSizeReduction': {'prompt_toolkit_series_i': 6},
                     'DistalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 7},
                     'DistalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 7},
                     'DistalPhalanxTW': {'prompt_toolkit_series_i': 3},
                     'DodgerLoopGame': {'prompt_toolkit_series_i': 7},
                     'DodgerLoopWeekend': {'prompt_toolkit_series_i': 5}, 'Earthquakes': {'prompt_toolkit_series_i': 4},
                     'ECG200': {'prompt_toolkit_series_i': 7}, 'ECG5000': {'prompt_toolkit_series_i': 5},
                     'ECGFiveDays': {'prompt_toolkit_series_i': 1}, 'ElectricDevices': {'prompt_toolkit_series_i': 3},
                     'EOGHorizontalSignal': {'prompt_toolkit_series_i': 7},
                     'EOGVerticalSignal': {'prompt_toolkit_series_i': 8},
                     'EthanolLevel': {'prompt_toolkit_series_i': 7}, 'FaceAll': {'prompt_toolkit_series_i': 2},
                     'FacesUCR': {'prompt_toolkit_series_i': 6}, 'Fish': {'prompt_toolkit_series_i': 4},
                     'FordA': {'prompt_toolkit_series_i': 3}, 'FordB': {'prompt_toolkit_series_i': 6},
                     'FreezerRegularTrain': {'prompt_toolkit_series_i': 2},
                     'FreezerSmallTrain': {'prompt_toolkit_series_i': 3},
                     'GesturePebbleZ1': {'prompt_toolkit_series_i': 4},
                     'GesturePebbleZ2': {'prompt_toolkit_series_i': 4}, 'GunPoint': {'prompt_toolkit_series_i': 1},
                     'GunPointAgeSpan': {'prompt_toolkit_series_i': 2},
                     'GunPointMaleVersusFemale': {'prompt_toolkit_series_i': 3},
                     'GunPointOldVersusYoung': {'prompt_toolkit_series_i': 4}, 'Ham': {'prompt_toolkit_series_i': 3},
                     'HandOutlines': {'prompt_toolkit_series_i': 8}, 'Haptics': {'prompt_toolkit_series_i': 7},
                     'Herring': {'prompt_toolkit_series_i': 2}, 'HouseTwenty': {'prompt_toolkit_series_i': 7},
                     'InlineSkate': {'prompt_toolkit_series_i': 4},
                     'InsectEPGRegularTrain': {'prompt_toolkit_series_i': 1},
                     'InsectEPGSmallTrain': {'prompt_toolkit_series_i': 5},
                     'InsectWingbeatSound': {'prompt_toolkit_series_i': 6},
                     'ItalyPowerDemand': {'prompt_toolkit_series_i': 1},
                     'LargeKitchenAppliances': {'prompt_toolkit_series_i': 5},
                     'Lightning2': {'prompt_toolkit_series_i': 7}, 'Mallat': {'prompt_toolkit_series_i': 1},
                     'Meat': {'prompt_toolkit_series_i': 1}, 'MedicalImages': {'prompt_toolkit_series_i': 4},
                     'MelbournePedestrian': {'prompt_toolkit_series_i': 6},
                     'MiddlePhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 1},
                     'MiddlePhalanxOutlineCorrect': {'prompt_toolkit_series_i': 6},
                     'MiddlePhalanxTW': {'prompt_toolkit_series_i': 1},
                     'MixedShapesRegularTrain': {'prompt_toolkit_series_i': 6},
                     'MixedShapesSmallTrain': {'prompt_toolkit_series_i': 2},
                     'MoteStrain': {'prompt_toolkit_series_i': 7},
                     'NonInvasiveFetalECGThorax1': {'prompt_toolkit_series_i': 3},
                     'NonInvasiveFetalECGThorax2': {'prompt_toolkit_series_i': 3},
                     'OSULeaf': {'prompt_toolkit_series_i': 3},
                     'PhalangesOutlinesCorrect': {'prompt_toolkit_series_i': 5},
                     'Phoneme': {'prompt_toolkit_series_i': 3}, 'PLAID': {'prompt_toolkit_series_i': 1},
                     'Plane': {'prompt_toolkit_series_i': 4}, 'PowerCons': {'prompt_toolkit_series_i': 8},
                     'ProximalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 8},
                     'ProximalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 3},
                     'ProximalPhalanxTW': {'prompt_toolkit_series_i': 3},
                     'RefrigerationDevices': {'prompt_toolkit_series_i': 7},
                     'ScreenType': {'prompt_toolkit_series_i': 6}, 'SemgHandGenderCh2': {'prompt_toolkit_series_i': 4},
                     'SemgHandMovementCh2': {'prompt_toolkit_series_i': 5},
                     'SemgHandSubjectCh2': {'prompt_toolkit_series_i': 7},
                     'ShapeletSim': {'prompt_toolkit_series_i': 3},
                     'SmallKitchenAppliances': {'prompt_toolkit_series_i': 1},
                     'SmoothSubspace': {'prompt_toolkit_series_i': 4},
                     'SonyAIBORobotSurface1': {'prompt_toolkit_series_i': 2},
                     'SonyAIBORobotSurface2': {'prompt_toolkit_series_i': 7},
                     'StarLightCurves': {'prompt_toolkit_series_i': 1}, 'Strawberry': {'prompt_toolkit_series_i': 4},
                     'SwedishLeaf': {'prompt_toolkit_series_i': 6}, 'Symbols': {'prompt_toolkit_series_i': 6},
                     'SyntheticControl': {'prompt_toolkit_series_i': 1},
                     'ToeSegmentation1': {'prompt_toolkit_series_i': 1},
                     'ToeSegmentation2': {'prompt_toolkit_series_i': 7}, 'Trace': {'prompt_toolkit_series_i': 6},
                     'TwoLeadECG': {'prompt_toolkit_series_i': 1}, 'TwoPatterns': {'prompt_toolkit_series_i': 2},
                     'UMD': {'prompt_toolkit_series_i': 4}, 'UWaveGestureLibraryAll': {'prompt_toolkit_series_i': 7},
                     'UWaveGestureLibraryX': {'prompt_toolkit_series_i': 2},
                     'UWaveGestureLibraryY': {'prompt_toolkit_series_i': 3},
                     'UWaveGestureLibraryZ': {'prompt_toolkit_series_i': 5}, 'Wafer': {'prompt_toolkit_series_i': 1},
                     'Wine': {'prompt_toolkit_series_i': 1}, 'WordSynonyms': {'prompt_toolkit_series_i': 8},
                     'Worms': {'prompt_toolkit_series_i': 4}, 'WormsTwoClass': {'prompt_toolkit_series_i': 4},
                     'Yoga': {'prompt_toolkit_series_i': 5}}

ucr_hyp_prompt_40 = {'AllGestureWiimoteX': {'prompt_toolkit_series_i': 1},
                     'AllGestureWiimoteY': {'prompt_toolkit_series_i': 5},
                     'AllGestureWiimoteZ': {'prompt_toolkit_series_i': 6}, 'ArrowHead': {'prompt_toolkit_series_i': 1},
                     'BME': {'prompt_toolkit_series_i': 4}, 'Car': {'prompt_toolkit_series_i': 3},
                     'CBF': {'prompt_toolkit_series_i': 1}, 'Chinatown': {'prompt_toolkit_series_i': 1},
                     'CinCECGTorso': {'prompt_toolkit_series_i': 7},
                     'ChlorineConcentration': {'prompt_toolkit_series_i': 1},
                     'Computers': {'prompt_toolkit_series_i': 8}, 'CricketX': {'prompt_toolkit_series_i': 6},
                     'CricketY': {'prompt_toolkit_series_i': 8}, 'CricketZ': {'prompt_toolkit_series_i': 1},
                     'Crop': {'prompt_toolkit_series_i': 8}, 'DiatomSizeReduction': {'prompt_toolkit_series_i': 7},
                     'DistalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 8},
                     'DistalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 1},
                     'DistalPhalanxTW': {'prompt_toolkit_series_i': 5},
                     'DodgerLoopGame': {'prompt_toolkit_series_i': 5},
                     'DodgerLoopWeekend': {'prompt_toolkit_series_i': 1}, 'Earthquakes': {'prompt_toolkit_series_i': 1},
                     'ECG200': {'prompt_toolkit_series_i': 5}, 'ECG5000': {'prompt_toolkit_series_i': 3},
                     'ECGFiveDays': {'prompt_toolkit_series_i': 2}, 'ElectricDevices': {'prompt_toolkit_series_i': 7},
                     'EOGHorizontalSignal': {'prompt_toolkit_series_i': 4},
                     'EOGVerticalSignal': {'prompt_toolkit_series_i': 4},
                     'EthanolLevel': {'prompt_toolkit_series_i': 4}, 'FaceAll': {'prompt_toolkit_series_i': 8},
                     'FacesUCR': {'prompt_toolkit_series_i': 8}, 'Fish': {'prompt_toolkit_series_i': 3},
                     'FordA': {'prompt_toolkit_series_i': 3}, 'FordB': {'prompt_toolkit_series_i': 2},
                     'FreezerRegularTrain': {'prompt_toolkit_series_i': 8},
                     'FreezerSmallTrain': {'prompt_toolkit_series_i': 4},
                     'GesturePebbleZ1': {'prompt_toolkit_series_i': 5},
                     'GesturePebbleZ2': {'prompt_toolkit_series_i': 5}, 'GunPoint': {'prompt_toolkit_series_i': 6},
                     'GunPointAgeSpan': {'prompt_toolkit_series_i': 8},
                     'GunPointMaleVersusFemale': {'prompt_toolkit_series_i': 6},
                     'GunPointOldVersusYoung': {'prompt_toolkit_series_i': 3}, 'Ham': {'prompt_toolkit_series_i': 7},
                     'HandOutlines': {'prompt_toolkit_series_i': 6}, 'Haptics': {'prompt_toolkit_series_i': 6},
                     'Herring': {'prompt_toolkit_series_i': 1}, 'HouseTwenty': {'prompt_toolkit_series_i': 1},
                     'InlineSkate': {'prompt_toolkit_series_i': 7},
                     'InsectEPGRegularTrain': {'prompt_toolkit_series_i': 2},
                     'InsectEPGSmallTrain': {'prompt_toolkit_series_i': 8},
                     'InsectWingbeatSound': {'prompt_toolkit_series_i': 3},
                     'ItalyPowerDemand': {'prompt_toolkit_series_i': 7},
                     'LargeKitchenAppliances': {'prompt_toolkit_series_i': 5},
                     'Lightning2': {'prompt_toolkit_series_i': 3}, 'Mallat': {'prompt_toolkit_series_i': 2},
                     'Meat': {'prompt_toolkit_series_i': 4}, 'MedicalImages': {'prompt_toolkit_series_i': 8},
                     'MelbournePedestrian': {'prompt_toolkit_series_i': 1},
                     'MiddlePhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 4},
                     'MiddlePhalanxOutlineCorrect': {'prompt_toolkit_series_i': 2},
                     'MiddlePhalanxTW': {'prompt_toolkit_series_i': 8},
                     'MixedShapesRegularTrain': {'prompt_toolkit_series_i': 4},
                     'MixedShapesSmallTrain': {'prompt_toolkit_series_i': 7},
                     'MoteStrain': {'prompt_toolkit_series_i': 5},
                     'NonInvasiveFetalECGThorax1': {'prompt_toolkit_series_i': 1},
                     'NonInvasiveFetalECGThorax2': {'prompt_toolkit_series_i': 5},
                     'OSULeaf': {'prompt_toolkit_series_i': 3},
                     'PhalangesOutlinesCorrect': {'prompt_toolkit_series_i': 8},
                     'Phoneme': {'prompt_toolkit_series_i': 1}, 'PLAID': {'prompt_toolkit_series_i': 5},
                     'Plane': {'prompt_toolkit_series_i': 4}, 'PowerCons': {'prompt_toolkit_series_i': 2},
                     'ProximalPhalanxOutlineAgeGroup': {'prompt_toolkit_series_i': 2},
                     'ProximalPhalanxOutlineCorrect': {'prompt_toolkit_series_i': 7},
                     'ProximalPhalanxTW': {'prompt_toolkit_series_i': 5},
                     'RefrigerationDevices': {'prompt_toolkit_series_i': 1},
                     'ScreenType': {'prompt_toolkit_series_i': 1}, 'SemgHandGenderCh2': {'prompt_toolkit_series_i': 6},
                     'SemgHandMovementCh2': {'prompt_toolkit_series_i': 8},
                     'SemgHandSubjectCh2': {'prompt_toolkit_series_i': 5},
                     'ShapeletSim': {'prompt_toolkit_series_i': 1},
                     'SmallKitchenAppliances': {'prompt_toolkit_series_i': 8},
                     'SmoothSubspace': {'prompt_toolkit_series_i': 2},
                     'SonyAIBORobotSurface1': {'prompt_toolkit_series_i': 4},
                     'SonyAIBORobotSurface2': {'prompt_toolkit_series_i': 1},
                     'StarLightCurves': {'prompt_toolkit_series_i': 6}, 'Strawberry': {'prompt_toolkit_series_i': 3},
                     'SwedishLeaf': {'prompt_toolkit_series_i': 5}, 'Symbols': {'prompt_toolkit_series_i': 4},
                     'SyntheticControl': {'prompt_toolkit_series_i': 1},
                     'ToeSegmentation1': {'prompt_toolkit_series_i': 7},
                     'ToeSegmentation2': {'prompt_toolkit_series_i': 6}, 'Trace': {'prompt_toolkit_series_i': 1},
                     'TwoLeadECG': {'prompt_toolkit_series_i': 7}, 'TwoPatterns': {'prompt_toolkit_series_i': 2},
                     'UMD': {'prompt_toolkit_series_i': 2}, 'UWaveGestureLibraryAll': {'prompt_toolkit_series_i': 8},
                     'UWaveGestureLibraryX': {'prompt_toolkit_series_i': 7},
                     'UWaveGestureLibraryY': {'prompt_toolkit_series_i': 4},
                     'UWaveGestureLibraryZ': {'prompt_toolkit_series_i': 6}, 'Wafer': {'prompt_toolkit_series_i': 2},
                     'Wine': {'prompt_toolkit_series_i': 6}, 'WordSynonyms': {'prompt_toolkit_series_i': 4},
                     'Worms': {'prompt_toolkit_series_i': 2}, 'WormsTwoClass': {'prompt_toolkit_series_i': 7},
                     'Yoga': {'prompt_toolkit_series_i': 6}}
